import type { ComponentType } from "react";
import { GrantCard } from "./components/GrantCard";
import { PendingApprovalCard } from "./components/PendingApprovalCard";
import { AuditTimeline } from "./components/AuditTimeline";

/**
 * The component registry: the contract between backend-api's UISpec (generated by
 * Gemini, ultimately) and what actually renders. A panel spec's `component` field must
 * match a key here — if Gemini names something that isn't registered, render a visible
 * fallback (below) rather than crashing, so a bad generation doesn't take the whole
 * dashboard down.
 */
export const COMPONENT_REGISTRY: Record<string, ComponentType<Record<string, unknown>>> = {
  GrantCard,
  PendingApprovalCard,
  AuditTimeline,
};

export function UnknownComponent(props: Record<string, unknown>) {
  return (
    <div className="card card-unknown">
      <div className="card-title">Unrecognized component</div>
      <pre>{JSON.stringify(props, null, 2)}</pre>
    </div>
  );
}
